version: '3'

services:
  app:
    build:
      args:
        ENVIRONMENT: ${ENVIRONMENT:-production}
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
    ports:
      - '80:80'

  worker:
    build:
      args:
        ENVIRONMENT: ${ENVIRONMENT:-production}

  redis:
    environment:
      - ALLOW_EMPTY_PASSWORD=no
